apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authgear-saml-sp-testing-tool-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: authgear-saml-sp-testing-tool.pandawork.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authgear-saml-sp-testing-tool
                port:
                  number: 80
  tls:
    - hosts:
        - authgear-saml-sp-testing-tool.pandawork.com
      secretName: authgear-saml-sp-testing-tool.pandawork.com
