name: Build Image

on:
  push:
    branches:
    - 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    if: ${{ github.repository == 'authgear/authgear-saml-sp-testing-tool' }}
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_ROBOT_TOKEN }}
        run: |
          printf "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" quay.io
      - run: make -C app push-image
      - name: docker logout
        if: ${{ always() }}
        run: |
          docker logout quay.io
  mirror:
    needs: ["builds"]
    if: ${{ github.repository == 'authgear/authgear-saml-sp-testing-tool' }}
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        # Set fetch-depth: 0 to fetch all history for all branches and tags.
        # https://github.com/actions/checkout#:~:text=Set%20fetch%2Ddepth%3A%200%20to%20fetch%20all%20history%20for%20all%20branches%20and%20tags.
        fetch-depth: 0
    - name: Import GitHub Deploy Key of the mirror repository
      env:
        MIRROR_GITHUB_DEPLOY_KEY: ${{ secrets.MIRROR_GITHUB_DEPLOY_KEY_OURSKY }}
      run: |
        mkdir -p ~/.ssh
        printf "$MIRROR_GITHUB_DEPLOY_KEY" | base64 --decode > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        if [ -e ~/.ssh/known_hosts ]; then ssh-keygen -R github.com; fi
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Mirror
      run: |
        export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_ed25519"
        # Print the git version for debugging purpose.
        git --version
        # Print the output of git show-ref for debugging purpose.
        git show-ref
        git remote add mirror git@github.com:oursky/authgear-saml-sp-testing-tool.git
        git push mirror --mirror
    - name: Clean up
      if: ${{ always() }}
      run: |
        rm -f ~/.ssh/id_ed25519
        git remote remove mirror
